from __future__ import annotations

import json
import os
import urllib.request
from typing import Any, Dict

from .types import Order, Session


def send_payment_confirmation_email(to_email: str, session: Session, order: Order) -> bool:
    """
    Send a payment confirmation email to the admin using Resend.
    Includes user phone, selected service, and a summary of chat selections.
    Returns True on success, False on failure.
    """
    api_key = os.getenv("RESEND_API_KEY")
    from_email = os.getenv("RESEND_FROM_EMAIL", "noreply@yourdomain.com")
    if not api_key:
        return False

    # Build a readable summary of selections
    summary_lines = [
        f"Service: {order.service_name}",
        f"Amount: TZS {order.amount_tzs}",
        f"Channel: {order.channel}",
        f"Order Token: {order.token}",
        f"Status: {order.status}",
        "",
        "User Info:",
        f"Phone (session ID): {session.session_id}",
        f"Language: {session.language or 'not set'}",
    ]

    # Include any stored selections (you can extend this as needed)
    if session.data:
        summary_lines.append("")
        summary_lines.append("Chat selections / context:")
        for k, v in session.data.items():
            summary_lines.append(f"- {k}: {v}")

    body_html = f"""
<html>
<body>
<h2>Afyabot Payment Confirmation</h2>
<p>A payment was received. Below are the details for the user and their order:</p>
<table>
  <tr><td><strong>Service</strong></td><td>{order.service_name}</td></tr>
  <tr><td><strong>Amount</strong></td><td>TZS {order.amount_tzs}</td></tr>
  <tr><td><strong>Channel</strong></td><td>{order.channel}</td></tr>
  <tr><td><strong>Order Token</strong></td><td>{order.token}</td></tr>
  <tr><td><strong>Status</strong></td><td>{order.status}</td></tr>
</table>
<h3>User Info</h3>
<ul>
  <li><strong>Phone (session ID):</strong> {session.session_id}</li>
  <li><strong>Language:</strong> {session.language or 'not set'}</li>
</ul>
<h3>Chat selections / context</h3>
<pre>
{chr(10).join(f"- {k}: {v}" for k, v in session.data.items()) if session.data else "None"}
</pre>
<p><em>This email was generated by Afyabot. Please contact the user if needed.</em></p>
</body>
</html>
"""

    payload = {
        "from": from_email,
        "to": [to_email],
        "subject": f"Afyabot Payment Confirmation – {order.service_name}",
        "html": body_html,
    }

    try:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        req = urllib.request.Request(
            "https://api.resend.com/emails",
            data=data,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
            result = json.loads(raw)
            return result.get("id") is not None
    except Exception:
        return False
